-- Inserting data into the books table
INSERT INTO books (name, testament)
VALUES
    ('genesis', 'Old'),
    ('exodus', 'Old'),
    ('leviticus', 'Old'),
    ('numbers', 'Old'),
    ('deuteronomy', 'Old'),
    ('joshua', 'Old'),
    ('judges', 'Old'),
    ('ruth', 'Old'),
    ('1 samuel', 'Old'),
    ('2 samuel', 'Old'),
    ('1 kings', 'Old'),
    ('2 kings', 'Old'),
    ('1 chronicles', 'Old'),
    ('2 chronicles', 'Old'),
    ('ezra', 'Old'),
    ('nehemiah', 'Old'),
    ('esther', 'Old'),
    ('job', 'Old'),
    ('psalms', 'Old'),
    ('proverbs', 'Old'),
    ('ecclesiastes', 'Old'),
    ('song of solomon', 'Old'),
    ('isaiah', 'Old'),
    ('jeremiah', 'Old'),
    ('lamentations', 'Old'),
    ('ezekiel', 'Old'),
    ('daniel', 'Old'),
    ('hosea', 'Old'),
    ('joel', 'Old'),
    ('amos', 'Old'),
    ('obadiah', 'Old'),
    ('jonah', 'Old'),
    ('micah', 'Old'),
    ('nahum', 'Old'),
    ('habakkuk', 'Old'),
    ('zephaniah', 'Old'),
    ('haggai', 'Old'),
    ('zechariah', 'Old'),
    ('malachi', 'Old'),

    
    -- Continue adding entries for all books in the Bible
    ('matthew', 'New'),
    ('mark', 'New'),
    ('luke', 'New'),
    ('john', 'New'),
    ('acts', 'New'),
    ('romans', 'New'),
    ('1 corinthians', 'New'),
    ('2 corinthians', 'New'),
    ('galatians', 'New'),
    ('ephesians', 'New'),
    ('philippians', 'New'),
    ('colossians', 'New'),
    ('1 thessalonians', 'New'),
    ('2 thessalonians', 'New'),
    ('1 timothy', 'New'),
    ('2 timothy', 'New'),
    ('titus', 'New'),
    ('philemon', 'New'),
    ('hebrews', 'New'),
    ('james', 'New'),
    ('1 peter', 'New'),
    ('2 peter', 'New'),
    ('1 john', 'New'),
    ('2 john', 'New'),
    ('3 john', 'New'),
    ('jude', 'New'),
    ('revelation', 'New');

    -- Continue adding entries for all books in the New Testament
